### ISSUE TITLE
DummyRandom does not work with ring v0.13.0-alpha5

### ISSUE THREAD

**Issue by realcr** [freedomlayer/offset#64]
In the latest update to ring v0.13.0-alpha5 we get the following compilation error:

```rust
error[E0277]: the trait bound `crypto::test_utils::DummyRandom<R>: ring::private::Sealed` is not satisfied
  --> src/crypto/test_utils.rs:23:14
   |
23 | impl<R: Rng> SecureRandom for DummyRandom<R> {
   |              ^^^^^^^^^^^^ the trait `ring::private::Sealed` is not implemented for `crypto::test_utils::DummyRandom<R>`

```

See also issue https://github.com/briansmith/ring/issues/661

I see three options to fix this:

1. Make our own trait that wraps SecureRandom. We can call it `RandomGenerator`. All of our code will work directly with RandomGenerator. This way we will not be affected by further changes to Ring's interface.
2. Hope that we can get DummyRandom into Ring.
3. Use `FixedSliceRandom` from Ring. However, I think that the interface of this random generator is very uncomfortable, because we have to predict exactly the amount of random bytes that will be requested every time.

Currently I think that option (1) is our best bet. @kamyuentse : What do you think?

**Comment by realcr** [comment]
Solved by https://github.com/freedomlayer/offset/pull/300
